name: termare_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  archive: ^3.1.2
  get: ^4.1.4
  flutter:
    sdk: flutter
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  cupertino_icons: ^1.0.2

  termare_pty:
    git: https://github.com/termare/termare_pty
  termare_view:
    git: https://github.com/termare/termare_view
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro.ttf
    - family: SourceCodeProMediumforPowerline
      fonts:
        - asset: assets/fonts/SourceCodeProMediumforPowerline.otf
    - family: MesloLGMforPowerline
      fonts:
        - asset: assets/fonts/MesloLGMforPowerline.ttf
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf
    - family: DroidSansMono
      fonts:
        - asset: assets/fonts/DroidSansMono.ttf

  assets:
    - assets/ogg/
    - assets/icons/
    - assets/lib/
    - assets/text/

dependency_overrides:
  termare_view:
    path: /Users/nightmare/Desktop/termare-space/termare_view
  termare_pty:
    path: /Users/nightmare/Desktop/termare-space/termare_pty
  dart_pty:
    path: /Users/nightmare/Desktop/termare-space/dart_pty
  global_repository:
    path: /Users/nightmare/Desktop/nightmare-space/global_repository