name: termare_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  custom_log:
    git:
      url: https://github.com/nightmare-space/custom_log
      ref: dart
  archive: ^2.0.13
  get: 4.1.3
  flutter:
    sdk: flutter
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  cupertino_icons: ^1.0.2
  # 网络访问插件
  dio: ^3.0.3
  termare_pty:
    path: ../../termare-space/termare_pty
  termare_view:
    path: ../../termare-space/termare_view

  dart_pty:
    path: ../../termare-space/dart_pty
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro.ttf
    - family: SourceCodeProMediumforPowerline
      fonts:
        - asset: assets/fonts/SourceCodeProMediumforPowerline.otf
    - family: MesloLGMforPowerline
      fonts:
        - asset: assets/fonts/MesloLGMforPowerline.ttf
    - family: MenloforPowerline
      fonts:
        - asset: assets/fonts/MenloforPowerline.ttf

  assets:
    - assets/ogg/
    - assets/images/
    - assets/icons/
    - assets/text/
    - assets/images/2.0x/
    - assets/images/3.0x/
